---
- name: Include default vars
  ansible.builtin.include_vars: defaults.yml
  tags: [netinstall, vars, netinstall:vars,
         config, netinstall:config, install, netinstall:install]

- name: Include OS-specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_lsb.id }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - defaults.yml
  tags: [netinstall, vars, netinstall:vars,
         config, netinstall:config, install, netinstall:install]

- name: Include OS-specific setup
  ansible.builtin.include_tasks:
    file: "{{ item }}"
    apply:
      tags: [netinstall, install, netinstall:install]
  with_first_found:
    - "install-{{ ansible_lsb.id }}-{{ ansible_lsb.major_release }}.yml"
    - "install-{{ ansible_lsb.id }}.yml"
    - "install-{{ ansible_distribution }}-\
      {{ ansible_distribution_major_version }}.yml"
    - "install-{{ ansible_distribution }}.yml"
    - "install-{{ ansible_os_family }}.yml"
    - "install.yml"
  tags: [netinstall, install, netinstall:install]

- name: configure
  ansible.builtin.import_tasks: config.yml
  tags: [netinstall, config, netinstall:config]
